#!/usr/bin/env python3
"""Regenerate ``custom_components/bmw_cardata/descriptors.py`` from the BMW
Telematics Data Catalogue.

Input: ``reference/telematics_data_catalogue.csv`` -- an export of the BMW
CarData "Telematics Data Catalogue" (TDC). Columns (0-indexed):

    1  CarData Element (long human label)
    2  Description
    3  Category
    4  Name (short label within the category)
    7  Technical descriptor (contains U+200B zero-width spaces -- stripped here)
    8  Data type
    9  Typical value range
    10 Unit

Usage:  python3 scripts/gen_descriptors.py
"""

from __future__ import annotations

import csv
import pathlib
import pprint

ROOT = pathlib.Path(__file__).resolve().parent.parent
CSV_PATH = ROOT / "reference" / "telematics_data_catalogue.csv"
OUT_PATH = ROOT / "custom_components" / "bmw_cardata" / "descriptors.py"

ZWSP = "​"


def _clean(value: str) -> str:
    return value.replace(ZWSP, "").replace(" ", " ").strip()


def _friendly_name(category: str, name: str, element: str) -> str:
    category = _clean(category)
    name = _clean(name)
    element = _clean(element)
    if category and name:
        combined = f"{category} {name}"
        # Avoid "Battery Battery ..." style stutter.
        if name.lower().startswith(category.lower()):
            combined = name
        return combined[:1].upper() + combined[1:]
    return element or name or category


def build() -> dict[str, dict]:
    descriptors: dict[str, dict] = {}
    with CSV_PATH.open(newline="", encoding="utf-8-sig") as handle:
        reader = csv.reader(handle)
        next(reader, None)  # header
        for row in reader:
            if len(row) < 11:
                continue
            technical = _clean(row[7])
            if not technical or not technical.startswith("vehicle."):
                continue
            unit = _clean(row[10])
            if unit in {"-", ""}:
                unit = None
            data_type = _clean(row[8]) or None
            value_range = _clean(row[9]) or None
            descriptors[technical] = {
                "name": _friendly_name(row[3], row[4], row[1]),
                "category": _clean(row[3]) or None,
                "data_type": data_type,
                "value_range": value_range,
                "unit": unit,
            }
    return descriptors


def render(descriptors: dict[str, dict]) -> str:
    body = pprint.pformat(descriptors, width=100, sort_dicts=True)
    return (
        '"""BMW CarData telematics descriptor catalogue.\n\n'
        "GENERATED by scripts/gen_descriptors.py from the BMW Telematics Data\n"
        "Catalogue -- do not edit by hand. Re-run the script to refresh.\n"
        '"""\n\n'
        "from __future__ import annotations\n\n"
        f"DESCRIPTORS: dict[str, dict] = {body}\n"
    )


def main() -> None:
    descriptors = build()
    OUT_PATH.write_text(render(descriptors), encoding="utf-8")
    print(f"Wrote {len(descriptors)} descriptors to {OUT_PATH.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
